version: "3.7"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - "./.data/mysql:/var/lib/mysql"
    healthcheck: # here
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s
    restart: on-failure

  # todo: migrationを導入する

  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    working_dir: "/work/src/"
    command: ["air", "-c", ".air.toml"]
    volumes:
      - ".:/work/src"
      - "./.data/go-pkg:/go/pkg/mod/cache"
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: on-failure
    environment:
      RELEASE_VERSION: LOCAL
      COMMIT_HASH: LOCAL
      MYSQL_HOST: "mysql:3306"
